version: "3"
services:
  issuer.vcs.com:
    container_name: ${ISS_VCS_HOST}
    image: ${VCS_IMAGE}:${VCS_TAG}
    environment:
      - VC_REST_HOST_URL=0.0.0.0:${ISS_VCS_PORT}
      - VC_REST_HOST_URL_EXTERNAL=https://${ISS_VCS_HOST}:${ISS_VCS_PORT}
      - EDV_REST_HOST_URL=http://${EDV_HOST}:${EDV_PORT}
      - SIDETREE_HOST_URL=https://${STM_HOST}:${STM_PORT}/document
      - UNIVERSAL_RESOLVER_HOST_URL=http://${RES_HOST}:${RES_PORT}/1.0/identifiers
      - BLOC_DOMAIN=${BLOC_DOMAIN}
      - VC_REST_MODE=issuer
      - DATABASE_TYPE=mem
      - VIRTUAL_HOST=issuer.vcs.com
      - VC_REST_TLS_SYSTEMCERTPOOL=true
      - VC_REST_TLS_CACERTS=/etc/tls/trustbloc-dev-ca.crt
    ports:
      - ${ISS_VCS_PORT}:${ISS_VCS_PORT}
    entrypoint: ""
    # wait 5 seconds for couchdb to start
    command:  /bin/sh -c "sleep 10; vc-rest start"
    depends_on:
      - edv.com
      - sidetree-mock
      - uni-resolver-web
    volumes:
      - ../keys/tls:/etc/tls

  verifier.vcs.com:
    container_name: ${RP_VCS_HOST}
    image: ${VCS_IMAGE}:${VCS_TAG}
    environment:
      - VC_REST_HOST_URL=0.0.0.0:${RP_VCS_PORT}
      - VC_REST_HOST_URL_EXTERNAL=http://${RP_VCS_HOST}:${RP_VCS_PORT}
      - EDV_REST_HOST_URL=http://${EDV_HOST}:${EDV_PORT}
      - SIDETREE_HOST_URL=https://${STM_HOST}:${STM_PORT}/document
      - UNIVERSAL_RESOLVER_HOST_URL=http://${RES_HOST}:${RES_PORT}/1.0/identifiers
      - BLOC_DOMAIN=${BLOC_DOMAIN}
      - VC_REST_MODE=verifier
      - DATABASE_TYPE=mem
      - VIRTUAL_HOST=verifier.vcs.com
      - VC_REST_TLS_SYSTEMCERTPOOL=true
      - VC_REST_TLS_CACERTS=/etc/tls/trustbloc-dev-ca.crt
    entrypoint: ""
    # wait 5 seconds for couchdb to start
    command:  /bin/sh -c "sleep 10; vc-rest start"
    ports:
      - ${RP_VCS_PORT}:${RP_VCS_PORT}
    depends_on:
      - edv.com
      - sidetree-mock
      - uni-resolver-web
    volumes:
      - ../keys/tls:/etc/tls

  edv.com:
    container_name: ${EDV_HOST}
    image: ${EDV_IMAGE}:${EDV_TAG}
    environment:
      - EDV_HOST_URL=${EDV_HOST}:${EDV_PORT}
      - EDV_DATABASE_TYPE=couchdb
      - EDV_DATABASE_URL=http://${CDB_USER}:${CDB_PASSWORD}@${CDB_HOST}:${CDB_PORT}
    ports:
      - ${EDV_PORT}:${EDV_PORT}
    command: start

  sidetree-mock:
    container_name: ${STM_HOST}
    hostname: ${STM_HOST}
    image: ${STM_IMAGE}:${STM_TAG}
    environment:
      - SIDETREE_MOCK_TLS_CERTIFICATE=/etc/sidetree/tls/trustbloc-dev-ca.crt
      - SIDETREE_MOCK_TLS_KEY=/etc/sidetree/tls/trustbloc-dev-ca.key
      - SIDETREE_MOCK_HOST=${STM_HOST}
      - SIDETREE_MOCK_PORT=${STM_PORT}
      - SIDETREE_MOCK_DID_NAMESPACE=did:trustbloc:testnet.trustbloc.local
    ports:
      - ${STM_PORT}:${STM_PORT}
    volumes:
      - ../keys/tls:/etc/sidetree/tls
