version: '3'

services:

  wallet:
    build:
      context: ..
      dockerfile: wallet/Dockerfile
    environment:
      TLS_CERT: ${TLS_CERT_PATH}
      TLS_KEY: ${TLS_KEY_PATH}
      JWT_KEY: ButterChickChickChicken
      HOST: ${WAL_HOST}:${WAL_PORT}
    ports:
      - ${WAL_PORT}:${WAL_PORT}