version: "3"

services:
  vc-rest:
    container_name: vc-rest.com
    image: ${VCS_IMAGE}:${VCS_TAG}
    environment:
      - VC_REST_HOST_URL=vc-rest.com:8085
      - VC_REST_HOST_URL_EXTERNAL=http://vc-rest.com:8085
      - EDV_REST_HOST_URL=http://edv.com:8084
      - SIDETREE_HOST_URL=http://sidetree-mock.com:48326/document
    ports:
      - "8085:8085"
    command: start
    depends_on:
      - edv

  edv:
    container_name: edv.com
    image: ${EDV_IMAGE}:${EDV_TAG}
    environment:
      - EDV_HOST_URL=edv.com:8084
      - EDV_DATABASE_TYPE=couchdb
      - EDV_DATABASE_URL=admin:securekey@couchdb.com:5984
    ports:
      - "8084:8084"
    command: start

  sidetree:
    container_name: sidetree-mock.com
    image: ${STM_IMAGE}:${STM_TAG}
    environment:
      - SIDETREE_MOCK_PORT=48326
    ports:
      - 48326:48326