version: "3"

services:

  issuer:
    container_name: issuer
    build:
      context: ..
      dockerfile: issuer/Dockerfile
    ports:
    - "8080:8080"

  vc-rest:
    container_name: vcservice
    image: ${VCS_IMAGE}:${VCS_TAG}
    ports:
    - "8070:8070"
    depends_on:
      - edv

  edv:
    container_name: edv
    image: ${EDV_IMAGE}:${EDV_TAG}
