version: '3'

services:

  couchdb:
    container_name: couchdb.com
    build:
      context: ../issuer/couchdb/
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: securekey
    ports:
      - "5984:5984"
