version: "3"

services:

  issuer:
    container_name: issuer.com
    build:
      context: ..
      dockerfile: issuer/Dockerfile
    environment:
      TLS_CERT: /keys/tls/localhost.crt
      TLS_KEY: /keys/tls/localhost.key
      HOST: ${ISS_HOST}
    ports:
    - "8080:8080"
