version: "3"

services:

  verifier:
    container_name: verifier.com
    build:
      context: ..
      dockerfile: verifier/Dockerfile
    environment:
      TLS_CERT: /keys/tls/localhost.crt
      TLS_KEY: /keys/tls/localhost.key
    ports:
      - "8081:8081"
