version: '3'

services:

  couchdb:
    container_name: couchdb
    image: ${CDB_IMAGE}:${CDB_TAG}
    restart: always
    ports:
      - "5984:5984"
    environment:
      - "COUCHDB_USER=admin"
      - "COUCHDB_PASSWORD=securekey"