
# Web App Networking Config ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
issuer:
  host: localhost
  port: 8080

wallet:
  host: localhost
  port: 8082

verifier:
  host: localhost
  port: 8081

keys:
  cert_path: /keys/tls/localhost.crt
  key_path: /keys/tls/localhost.key

# Docker Image Info Config ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
couchdb:
  image: couchdb
  tag: latest
  user: admin
  password: securekey
  port: 5984

vc_rest:
  image: docker.pkg.github.com/trustbloc/edge-service/vc-rest
  tag: 0.1.3-snapshot-ab98ce5
  host: localhost
  port: 8085

edv:
  image: docker.pkg.github.com/trustbloc/edv/edv-rest
  tag: 0.1.2
  database_type: couchdb
  host: localhost
  port: 8084

sidetree:
  image: docker.pkg.github.com/trustbloc/sidetree-mock/sidetree
  tag: amd64-0.1.2
  host: localhost
  port: 48326

resolver:
  image: universalresolver/uni-resolver-web
  tag: latest
  host: localhost
  port: 8086